<?php

namespace AppBundle\Repository;

/**
 * SharedCollectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SharedCollectionRepository extends \Doctrine\ORM\EntityRepository
{
}
